website/auth.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from . import db
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user, login_required, current_user
auth = Blueprint("auth", __name__)


@auth.route("/login", methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get("email")
        password = request.form.get("password")

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Password is incorrect', category='error')
        else:
            flash('Email does not exist', category='error')

    return render_template("login.html", user=current_user)


@auth.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("views.home"))


@auth.route("/signup", methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        username = request.form.get("username")
        first_name = request.form.get("firstname")
        last_name = request.form.get("lastname")
        email = request.form.get("email")
        password1 = request.form.get("password1")
        password2 = request.form.get("password2")

        username_exists = User.query.filter_by(username=username).first()
        email_exists = User.query.filter_by(email=email).first()

        if username_exists:
            flash('Username already taken, choose another username.', category="error")
        elif email_exists:
            flash('Email Address already taken, choose another username.', category="error")
        elif password1 != password2:
            flash('Password do not match!', category='error')
        elif len(username) < 2:
            flash('Username is too short!', category='error')
        elif len(password1) < 6:
            flash('Password is too short!', category='error')
        elif len(email) < 4:
            flash('Email is invalid', category='error')
        else:
            new_user = User(username=username, first_name=first_name, last_name=last_name, email=email, password=generate_password_hash(password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('User created successfully!')
            return redirect(url_for('auth.login'))

    return render_template("signup.html", user=current_user)

website/templates/about.html
{% extends 'base.html' %}
{% block title %} ABOUT ME{% endblock %}
{% block content %}

<style>
.images{
margin-left: 500px;
width: 300px;
height: 350px;
border-radius: 200px;

}

.content{
color: rgb(3, 90, 54);

}

.about{
color: rgb(3, 90, 54);
padding-left: 100px;
padding-right: 100px;
}
</style>


<h1 align="center" style="padding: 50px; color: rgb(3, 90, 54); font-size: 100px;">ABOUT ME</h1>

   <img class="images"
            src="{{url_for('static',filename= 'images/mypicture.jpg')}}"
  >
<div class="content">
{% if current_user.is_authenticated %}
<h2 align="center">Hello, {{ current_user.username }}!, Welcome to my blog!</h2>
{% else %}
<h2 align="center">Welcome to my blog! </h2>
{% endif %}


   </div>
<br>

<div class="about">
  <p>I am a 22 year old from Lagos, Nigeria. I am currently enrolled in Altschool Africa studying Backend Engineering(Python).

</p>

<p>Self-love can be extremely difficult to come by. I discovered that my self-love & confidence came from fashion and web development.
</p>
  <p> My message for my fashion blog is to encourage everyone to dress in whatever you want, whatever makes you feel empowered & yourself. I encourage everyone to try that funky outfit & go out of your comfort zone. I want to help share tips & ideas that you can put into your own lifestyle to fit you. I want everyone to experience that confidence we all deserve to have.
</p>
<p>

I hope my blog does all these things & more for you. Let's boost our confidence & love ourselves fully. Even if it’s one day at a time.
</p>
  <p>
  Kindly note that Authentication is not required to go through posts on this blog, but you'll have
  to <a href="{{url_for('auth.login')}}">log in </a> to post, like, comment, edit or delete your
  articles.
</p>

<h4 align="center">
 Thank you,
    <br>
Luchee Space.
    </h4>
  </div>
{% endblock %}

website/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/6bbd273a9f.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"> </script>
    <title>{% block title%}{% endblock %}</title>
</head>
<style>
    .navbar-brand{
    padding-right: 700px;
    padding-left: 20px;
    margin: 10px;
    color: rgb(3, 90, 54);
    font-style: bold;
    font-size: 30px;
    font-family: 'Times New Roman', Times, serif;
    }


    img{
        align-self: center;
        padding-bottom: 50px;
    }
   .alert alert-danger d-flex align-items-center{
   padding: 10px;
   }
   .bi flex-shrink-0 me-2{
   padding: 10px;
   }
   .form-control{
   width: 100%;
   }

   @media (max-width: 840px) {
    .container {
      width: 100%;
      padding: 1rem;
       }
    }
    footer{
    margin-top: 100px;
    padding: 20px;
    color: rgb(3, 90, 54);
}
.images{
padding-left: 400px;
padding-top: 50px;
}

.fa-instagram{
  color:  rgb(3, 90, 54);
  padding-left: 600px;
  padding-top: 50px;
  font-size: 60px;
}

.fa-instagram:hover{
 cursor: pointer;
 color:rgb(206, 170, 9);
  }

  .fa-twitter{
    color: rgb(3, 90, 54);
  padding-top: 50px;
  padding-left: 20px;
  font-size: 60px;
  }

  .fa-twitter:hover{
    cursor: pointer;
    color:rgb(206, 170, 9);
  }

  .fa-github{
    color: rgb(3, 90, 54);
  padding-top: 50px;
  padding-left: 20px;
  font-size: 60px;
  }
  .fa-github:hover{
    cursor: pointer;
    color:rgb(206, 170, 9);
  }
  .fa-whatsapp{
    color: rgb(3, 90, 54);
  padding-top: 50px;
  padding-left: 20px;
  font-size: 60px;
  }
  .fa-whatsapp:hover{
    cursor: pointer;
    color:rgb(206, 170, 9);
  }





    
</style>
<body>
<header>
   <nav class="navbar navbar-expand-lg navbar-light bg-warning">
    <a class="navbar-brand" href="#">
    <img src="https://i.pinimg.com/originals/08/d9/3d/08d93df316cb19390ddb1e575eab05ec.jpg" alt="Logo" style="width:40px; padding-top: 50px; " class="rounded-pill">

    LUCHEE SPACE
        </a>


    <div class="container-fluid">
        <button class="navbar-toggler bg-warning"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbar"
        >
            <span class="navbar-toggler-icon bg-light"></span>
        </button>
        <div class="collapse navbar-collapse " id="navbar">
          <div class="navbar-nav" >
          <a class="nav-item nav-link" href="/home" style="color: rgb(3, 90, 54); font-size: 20px;">Home</a>
          {% if user.is_authenticated %}
           <a class="nav-item nav-link" href="/logout" style="color: rgb(3, 90, 54); font-size: 20px;">Log out</a>
              <a class="nav-item nav-link" href="/about" style="color: rgb(3, 90, 54); font-size: 20px;">About</a>
          <a class="nav-item nav-link" href="/contact" style="color: rgb(3, 90, 54); font-size: 20px;">Contact</a>
          {% else %}
          <a class="nav-item nav-link" href="/login" style="color: rgb(3, 90, 54); font-size: 20px;">Login</a>
          <a class="nav-item nav-link" href="/signup" style="color: rgb(3, 90, 54); font-size: 20px;">Sign Up</a>
          <a class="nav-item nav-link" href="/about" style="color: rgb(3, 90, 54); font-size: 20px;">About</a>
          <a class="nav-item nav-link" href="/contact" style="color: rgb(3, 90, 54); font-size: 20px;">Contact</a>
              {% endif %}
          </div>
        </div>
     </div>
</nav>
    </header>

<!-- code to create alert warning sign-->
   {% with messages = get_flashed_messages(with_categories=True) %}
<div class="container">
     {% if messages %}
       {% for category, message in messages %}
       {% if category == 'error' %}




   <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
       <symbol id="exclamation-triangle-fill" viewBox="0 0 16 16" >
    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
  </symbol>
</svg>
       <div class="alert alert-danger d-flex align-items-center" role="alert" >
  <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
  <div>
    {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss = "alert"></button>
  </div>
</div>
       {% else %}
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="check-circle-fill" viewBox="0 0 16 16">
    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
  </symbol>
</svg>
       <div class="alert alert-success d-flex align-items-center" role="alert" >
  <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
  <div>
    {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss = "alert"></button>
  </div>
</div>
       {% endif %}

       {% endfor %}
     {% endif %}
    </div>
   {% endwith %}
   
   
   
<!-- Social media icons-->

 <a href="https://instagram.com/oluchiiiruth/">
  <i class="fa-brands fa-instagram"  ></i>
 </a>
 <a href="https://twitter.com/AlikaOluchi">
  <i class="fa-brands fa-twitter"></i>
 </a>
 <a href="https://github.com/Lucheee/">
  <i class="fa-brands fa-github"></i>
 </a>
 <a href="https://wa.me/message/23PQSWVCAE3SA1">
 <i class="fa-brands fa-whatsapp"></i>
 </a>
 
 


  <main> <div class="container">{% block content %} {% endblock %}</div></main>
 <footer class="navbar navbar-expand-lg navbar-light" style="background-color: rgb(192, 139, 3);">
         <p class="footer">
           <b> &copy: LucheeSpace
        <script>
          document.write(new Date().getFullYear());
        </script>
        </b>
         </p>
    </footer>
<!--<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
-->
<script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js')}}">

</script>

</body>
</html>

website/templates/contact.html
{% extends 'base.html' %} 

{% block title %}
Contact {% endblock %}{% block content %}
<style>
 .btn:hover{
       background-color: rgb(1, 32, 1);
       color: white;
       transition-duration: 0.5s;
    }
</style>

<h1 align="center" style="font-size: 100px; padding-top: 50px; color: rgb(3, 90, 54);"> Contact Me</h1>
<br>
<br>


<h4 align="center" style="color: rgb(3, 90, 54);">Want to Collab?
    <br>
  <br>
Have a blog post
    <br>
  <br>
you'd like to see?
</h4>
    <br>
  <br>
<br>
<h3 align="center" style="color: rgb(3, 90, 54);">Let me know here!</h3>
<br>


<br>
<!-- Form to submit for Complaints-->
<form class="row g-3">
  <div class="col-md-6">
    <label for="name" class="form-label">Name</label>
    <input type="text" class="form-control" id="name" name="name" placeholder="Your name here">
  </div>
  <div class="col-md-6">
    <label for="email" class="form-label">Email Address</label>
    <input type="email" class="form-control" id="email" name="email" placeholder="Your email" required>
  </div>
  <div class="col-12">
    <label for="tel" class="form-label">Phone</label>
    <input type="tel" class="form-control" id="tel" placeholder="Your phone number">
  </div>
  <div class="col-12">
    <label for="title" class="form-label">Title</label>
    <input
            id="title"
      type="text"
      name="title"
      class="form-control"
      placeholder="What's Your Message About?"
      required
    >
  </div>
  <div class="col-md-6">
    <label for="message" class="form-label">Message</label>
<textarea
            id="message"
      name="message"
      cols="30"
      rows="10"
      class="form-control"
      placeholder="Type your Message Here"
      required
    ></textarea>  </div>

  <div class="col-12">
<button type="submit" class="btn btn-lg btn-warning">Submit</button>  </div>
</form>

{% endblock %}

website/templates/create_post.html
{% extends "base.html" %}
{% block title %} Home {% endblock %}
{% block content %}
<style>
    .btn:hover{
       background-color: rgb(1, 32, 1);
       color: white;
       transition-duration: 0.5s;
    }
    h1{
    padding: 20px;
    color: rgb(3, 90, 54);
    }
</style>
<h1 align="center">Post Something</h1>

<form method="POST">
    <div class="form-group">
    <label for="title">Title</label>
    <input
            id="title"
      type="text"
      name="title"
      class="form-control"
      placeholder="What's Your Post About?"
      required
    />
  </div>
    <br>
     <div class="form-group">
    <label for="content">Content</label>
    <textarea name="content" id="content" class="form-control" placeholder="Create Post"></textarea>
  </div>

    <br>
    <div align="center">
        <button type="submit" class="btn btn-lg btn-warning">Post</button>
    </div>


<br>
<div align="center">
   <a href="/home":>
    <button type="submit" class="btn btn-lg btn-secondary">Back</button></a>
</div>
</form>
{% endblock %}

website/templates/edit.html
{% extends 'base.html' %}
{% block title %} Edit post
{% endblock %}{% block content %}
<style>
      .btn:hover{
       background-color: rgb(1, 32, 1);
       color: white;
       transition-duration: 0.5s;
    }
    h3{
    padding: 20px;
    color: rgb(3, 90, 54);
    }
</style>
<form action="/edit/{{post.id}}/" method="POST">
  <div class="form-group">
    <h3>Edit Your Post</h3>
  </div>
  <div class="form-group">
    <label for="title">Title</label>
    <input
            id="title"
      type="text"
      name="title"
      class="form-control"
      value="{{post.title}}"
    />
  </div>
  <div class="form-group">
    <label for="content">Content</label>
    <textarea id="content" name="content" cols="50" rows="10" class="form-control">{{post.content}}</textarea>
  </div>
  <br>
    <div align="center">
        <button type="submit" class="btn btn-lg btn-warning">Post</button>
    </div>


<br>
<div align="center">
   <a href="/home":>
    <button type="submit" class="btn btn-lg btn-secondary">Back</button></a>
</div>
</form>
{% endblock %}

website/templates/home.html
{% extends "posts_div.html" %}
{% block title %} Home {% endblock %}

website/templates/login.html
{% extends "base.html" %}
{% block title %} Login {% endblock %}
{% block content %}
<style>
    h3{
        
        color: rgb(3, 90, 54);
        padding: 20px;
         }

    .btn:hover{
       background-color: rgb(1, 32, 1);
       color: white;
       transition-duration: 0.5s;
    }

    .form-control{
        width: 100%;
        border-radius: 20px;
    }
    .container{
    width: 600px;
    }
</style>

<form method="post">
    <h3 align="center">Log into your Lucheespace account</h3>
   <div class="container">
    <div class="form-floating mb-3">
        <input type="email" class="form-control border-success" name = "email"  id="floatingInput" placeholder="Email Address">
        <label for="floatingInput">Email address</label>
      </div>
      <div class="form-floating">
        <input type="password" class="form-control border-success" name = "password" id="floatingPassword" placeholder="Password">
        <label for="floatingPassword">Password</label>
          </div>
          <br>
          <div align="center">
              <button class="btn btn-warning" type="submit">Login</button>
</div>
      </div>

</form>

{% endblock %}

website/templates/posts.html
{% extends "posts_div.html" %} {% block title %}{{username}}'s Posts{% endblock
%} {% block header %} {{username}}'s posts {% endblock %} {% block footer %}
<div align="center">
  <a href="/home"
    ><button type="button" class="btn btn-warning btn-lg">Back</button></a
  >
</div>
{% endblock %}

website/templates/posts_div.html
{% extends "base.html" %}
{% block title %} Home {% endblock %}
{% block content %}
<style>
    .card-body{
    color: rgb(3, 90, 54);
    }
</style>
<h1 align="center" style="padding: 20px; color:rgb(3, 90, 54); ">{% block header %}Posts{% endblock %}</h1>
<div id="posts">
{% for post in posts %}

<div class="card border-dark">
    <div class="card-header d-flex justify-content-between align-items-center">
        <a href="/posts/{{ post.user.username }}" style="color: brown; font-size: 30px;">{{ post.user.username }}</a>
        <!--Likes functionality -->
        <div>
           <span id="likes-count-{{post.id}}">
        {{ post.likes|length }}</span>
        {% if user.id in post.likes|map(attribute="author")|list %}
        <i
          class="fa-solid fa-heart"
          id="like-button-{{post.id}}"
          onclick="like({{post.id}})"
        ></i>
        {% else %}
        <i
          class="fa-regular fa-heart"
          id="like-button-{{post.id}}"
          onclick="like({{post.id}})"
        ></i>
        {% endif %}

            {% if user.id == post.author %}
            <div class="btn-group">
            <button type="button" class="btn btn-sm btn-success dropdown-toggle" data-bs-toggle="dropdown">
            </button>
            <ul class="dropdown-menu">
                <li> <a href="/delete-post/{{ post.id }}" class="dropdown-item">Delete</a> </li>
                <li><a href="/edit/{{ post.id }}" class="dropdown-item">Edit Post</a></li>
            </ul>
        </div>
            {% endif %}
            </div>

    </div>
    <div class="card-body">
        <div class="card-text"><h1>{{ post.title }}</h1></div>
        <br>
        <div class="card-text"><h4>{{ post.content }}</h4></div>
        <h6>{{post.date_created.strftime('%d/%b/%Y')}}</h6>
        <br>
        <div class="collapse" id="comments-{{ post.id }}">
            <div class="card">
                <div class="card-body" id="comments-expanded-{{ post.id }}">
                    {% for comment in post.comments %}
                    <div class="d-flex justify-content-between align-items-center">
                        <div>
                            <a href="/posts/{{ comment.user.username }}">
                            {{ comment.user.username }}
                        </a> : {{ comment.content }}
                            </div>
                    <div>
                        <small class="text.muted">
                            {{ comment.date_created }}
                        </small>
                        {% if user.id == post.author %}
                         <div class="btn-group">
            <button type="button" class="btn btn-sm btn-success dropdown-toggle" data-bs-toggle="dropdown">
            </button>
            <ul class="dropdown-menu">
                <li> <a href="/delete-comment/{{ comment.id }}" class="dropdown-item">Delete</a> </li>
            </ul>
        </div>
                     {% endif %}
                    </div>
                    </div>

                    {% endfor %}
                </div>
            </div>
        </div>
        <p class="card-text">
        {% if post.comments|length > 0 %}
        <a data-bs-toggle="collapse" href="#comments-{{ post.id }}" role="button">
            <small>View {{ post.comments|length}} Comments</small>
            </a>
        {% else %}
        <small class="text-muted">No comments</small>
        {% endif %}
        </p>
              <form class="input-group mb-3" method="POST" action="/create-comment/{{post.id}}">
    <input type="text" id="text" name="text" class="form-control" placeholder="Comment something!">
    <button type="submit" class="btn" style="background-color: rgb(3, 90, 54); color: gold; ">Comment</button>
</form>
    </div>
    <div class="card-footer text-muted">{{ post.date_created }}</div>

</div>
    <br>
{% endfor %}
    </div>
{% block footer %}
   <div align="center">
       <a href="/create-post">
        {% if current_user.is_authenticated %}
          <button type="button" class="btn btn-lg" style="background-color: rgb(3, 90, 54); color: gold; ">
           Create a post
       </button></a>
       {% else %}
       <a href="{{url_for('auth.signup')}}" style="color: rgb(3, 90, 54); font-size: 30px;"> <b> Click here to get started </b> </a> 
       {% endif %}
   </div>

{% endblock %}

{% endblock %}

website/templates/signup.html
{% extends "base.html" %}
{% block title %} Signup {% endblock %}
{% block content %}
<style>
    h3{
        padding: 20px;
        color: rgb(3, 90, 54);
    }

    .btn:hover{
       background-color: rgb(1, 32, 1);
       color: white;
       transition-duration: 0.5s;
    }

    .form-control{
        border-radius: 20px;
    }

    .form-select{
        border-radius: 20px;
    }

    .container{
    width: 600px;
    }
</style>

<form method="post">
    <h3 align="center">Create an account today!</h3>
 <div class="container">
      <div class="form-floating mb-3">
        <input type="firstname" class="form-control border-success" name="firstname"  id="floatingFirstname" placeholder="Enter your firstname">
        <label for="floatingInput">Firstname</label>
      </div>
      <div class="form-floating mb-3">
        <input type="lastname" class="form-control border-success" name="lastname"  id="floatingLastname" placeholder="Enter your lastname">
        <label for="floatingInput">Lastname</label>
      </div>
    <div class="form-floating mb-3">
        <input type="username" class="form-control border-success" name="username"  id="floatingUsername" placeholder="Enter your preferred username">
        <label for="floatingInput">Username</label>
      </div>
      <div class="form-floating">
        <input type="email" class="form-control border-success" name = "email" id="floatingInput" placeholder="Email Address">
        <label for="floatingInput">Email Address</label>
      </div>

      <br>
      <div class="form-floating">
        <input type="password" class="form-control border-success" name = "password1" id="floatingPassword1" placeholder="Password">
        <label for="floatingPassword1">Password</label>
      </div>
      <br>
      <div class="form-floating">
        <input type="password" class="form-control border-success" name = "password2" id="floatingPassword2" placeholder="Confirm Password">
        <label for="floatingPassword2">Confirm Password</label>
      </div>
      <br>
      <div class="form-floating">
        <select class="form-select border-success" id="floatingSelect" aria-label="Gender Select">
          <option selected>Gender</option>
          <option value="1">Male</option>
          <option value="2">Female</option>
          <option value="3">Prefer not to say</option>
        </select>
        <label for="floatingSelect"> Gender </label>
      </div>
    </div>
          <br>
          <div align="center">
              <button class="btn btn-warning" type="submit">Sign Up</button>

        </div>

</form>

{% endblock %}